### ISSUE TITLE
Impossibility of using an icon from a path containing spaces

### ISSUE THREAD

**Issue by OrthodoxWindows** [freedom7341/Progman-x64#1]
When selecting the icon on the property page of the item, it is not possible to use an icon from a path containing spaces. Use the DOS names for the path solves the issue.

**Comment by freedom7341** [comment]
will look into this. is this from the recent release build or a self-compile of the latest copy of the source?

**Comment by OrthodoxWindows** [comment]
It's in self-compile of the source : not in the latest version but in the version of April 2. I will test in the latest version.

**Comment by freedom7341** [comment]
i've been digging into this and while i can reliable reproduce it (using the steps you've mentioned), it's really difficult to track down where exactly this issue occurs.
