### ISSUE TITLE
Help dialogs already deprecated

### ISSUE THREAD

**Issue by OEMunlag** [freedom7341/Progman-x64#3]
The help buttons are deleted and deprecated in windows 11, instead, when selecting any help
When clicking any help button
![image](https://user-images.githubusercontent.com/87287937/163694815-2030471a-72da-43cf-8b44-597e62f97369.png)
![image](https://user-images.githubusercontent.com/87287937/163694820-a8e219d7-b4e3-432f-b49d-d902dcd7f349.png)
Progman crashes and you are left with nothing, and in the best case, it just opens edge about a legacy things, but it mostly crashes.

**Comment by OrthodoxWindows** [comment]
To solve this issue, you can replace winhlp32.exe (which is stored in C: Windows) by the version of Windows XP.

**Comment by OrthodoxWindows** [comment]
Then you can copy progman.exe into C:\Windows\System32 and progman.hlp in C:\Windows\Help

**Comment by OEMunlag** [comment]
Thing is that, not everyone is going to do so, so removing help dialogs
would help, also, they are already deprecated

**Comment by OrthodoxWindows** [comment]
No, help dialogs are not obsolete when it is in .chm format (as HTML files compiled). I suggest Freedom7341 to write a winhlp32.exe Windows XP version installation script, or rewrite the manual in the .chm format.

**Comment by OEMunlag** [comment]
Thing is that, even with that, sometimes clicking  a help link crashes
progman, which sometimes is annoying, removing it would prevent the
problems, also, help is already legacy for win 3.1 which wouldnt help in
most cases.

**Comment by OrthodoxWindows** [comment]
Applying my fix, the Help dialogs works impeccably. **Without issue.**

**Comment by freedom7341** [comment]
i've got a copy of winhlp32 from windows xp on my computer but if anyone has experience in creating newer help files or perhaps even integrating winhlp into progman that'd be an interesting route to take.

**Comment by freedom7341** [comment]
i'll remove help from the dialogs but not from the command bar for now.

**Comment by OrthodoxWindows** [comment]
Winevdm contains an open-source version of winhlp32 : https://github.com/otya128/winevdm/tree/master/winhlp32
It works less well than the original but maybe it can be useful... 
Maybe the sources of NT4 also contains WinHLP32 ?

For HTML, Windows 98 help contains a CHM version of the Program Manager manual.
However, the information contained inside are not quite the same. I think it would be better to rewrite it; I could take care of it soon.

**Comment by freedom7341** [comment]
NT4 source contains WinHLP, if you have documentation on how to create HTML help then I'd appreciate it very much.

**Comment by freedom7341** [comment]
Continue on issue #10.
