### ISSUE TITLE
"Browse" file dialog might not work (in some cases)

### ISSUE THREAD

**Issue by einstein910** [freedom7341/Progman-x64#6]
I am using this on Windows Hyper-V Server 2019 as a basic GUI (since this OS does not have one by design), and I noticed that the "browse" button does not work at all here, whereas it does in a normal Windows OS. This stripped-down OS is definitely missing a component here, because M$ removed the "browse" button from the "Run" dialog box as well, for the same reason.

I've tested OpenFileDialog() in a vb.net application and found that it works, but I've not looked to see how Progman is trying to do this - guessing it is a different method entirely. I'm not much of a C-guy either (barely a programmer at all), so I'll just pass along what I found and maybe it can be of use.

Thanks for working on this, I have found progman to be immensely helpful in my particular use case, along with the now open-sourced WinFile.

**Comment by freedom7341** [comment]
Progman uses an API that may not be available, if you know any open-source programs that I can look into with working browse dialogs on this it would be much appreciated. I know this same thing prevented me from using Progman on Windows PE.

**Comment by freedom7341** [comment]
Will look into redoing the file dialogs. They currently use an archaic function that only redirects to a newer but seemingly unavailable function (or perhaps the archaic function itself is unavailable). Will investigate soon.

**Comment by einstein910** [comment]
Excellent, thank you!

**Comment by freedom7341** [comment]
Would appreciate testing under Server Core like in your use case. Tested under Windows PE it seemed to work just fine (and it now uses the same function that most programs would use for the open file dialog) but PE may differ from Server Core in terms of what is supported. Closing for now and releasing the latest version, reopen this issue if you have any problems with it.

**Comment by einstein910** [comment]
Great! I will try it out and let you know what happens!
