### ISSUE TITLE
Set desktop wallpaper on login

### ISSUE THREAD

**Issue by freedom7341** [freedom7341/Progman-x64#7]
When Program Manager is the default shell, upon logging in the desktop background may be black or another color. Control Panel shows the previously selected wallpaper as being the current wallpaper. Seems to just not load the background? May possibly be fixed with SPI_SETDESKTOPWALLPAPER or similar.

**Comment by freedom7341** [comment]
Fixed with last commit

**Comment by OrthodoxWindows** [comment]
Its great !
